### ISSUE TITLE
Question: Is it possible to use composable inside of a string?

### ISSUE THREAD

**Issue by lhriley** [IBM/composable#109]
We have a `configMap` that we need to apply to integrate `ingress-nginx` with `datadog`. At the moment, we define this for each cluster, but we have another `configMap` with common metadata about the cluster.

This is what I'd like to do:

```
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: ingress-nginx-opentracing
  namespace: ingress-nginx

spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ingress-nginx-opentracing
      namespace: ingress-nginx

    data:
      opentracing_config: |
        {
          "environment": "{{ THIS VALUE IS DYNAMIC }}",
          "service": "nginx",
          "agent_url": "unix:///var/run/datadog/apm.socket",
          "operation_name_override": "nginx.handle",
          "sample_rate": 1,
          "dd.priority.sampling": true
        }
```

**Comment by xvzf** [comment]
This is not supported so far unfortunately. However, you might be interested in FluxCD & using post-build variable substitution (https://fluxcd.io/flux/components/kustomize/kustomization/#post-build-variable-substitution)
